show name from microsoft id
gausstalk/gausstalk-frontend pull request #12
Opened 2022-05-12 15:49 UTC by yonsweng

2022-05-12 15:51 UTC, yonsweng commented
logo192 is copied cuz of a error log at the browser.

2022-05-12 15:55 UTC, yonsweng commented
Can we maintain (one-app one-url one-js-file) policy like this pr? Or Is it not reasonable?

2022-05-12 16:02 UTC, YoohaBae requested changes

2022-05-12 16:02 UTC, YoohaBae commented on src/components/chat.js
> +class CustomNavbar extends React.Component {
I actually separated the CustomNavbar from the chat page as the navbar can be reused multiple times. I think we should separate the concept of components and pages. It seams reasonable that components are objects that are reused multiple times such as a navbar and pages are only used once (in this case, chat page).

2022-05-12 16:03 UTC, YoohaBae commented
> Can we maintain (one-app one-url one-js-file) policy like this pr? Or Is it not reasonable?

I think this is reasonable in the sense that the one-js-file is a page file. Multiple component js files should be allowed and the page js file can just import the component js files.

2022-05-12 23:38 UTC, yonsweng commented
> > Can we maintain (one-app one-url one-js-file) policy like this pr? Or Is it not reasonable?
> 
> 
> 
> I think this is reasonable in the sense that the one-js-file is a page file. Multiple component js files should be allowed and the page js file can just import the component js files.

Agree. By the way, I think components that are shared over multi pages should be in the different js files.

2022-05-15 12:59 UTC, YoohaBae commented on src/components/auth.js
> +    var loginMessage = document.getElementById('login-message');
I think using let is a better convention for defining variables.
var allows to declare variables with the same name multiple times while let does not allow it.
Using let can help prevent overwriting important variables.
I wasn't aware of this but maybe we should consider let in the future.

2022-05-16 12:26 UTC, YoohaBae approved these changes
lgtm

2022-05-16 12:30 UTC, merged